import React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Header } from "@/src/feature/layouts/Header";
import { Footer } from "@/src/feature/layouts/Footer";

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
import { ThemeProvider } from "@/src/theme/ThemeProvider"
import clsx from 'clsx';

type RootLayoutProps = ({ children: React.ReactNode })


export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en" className='h-full'>
      <body className={clsx(inter.className, 'bg-background h-full')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem 
        >
           <div className='flex flex-col h-full'>
           <Header/>
            <div className='flex-1 max-w-lg  m-auto py-12  w-full'>{children}</div>
            <Footer/>
          </div>
        </ThemeProvider>
      </body>
    </html>

  )
}